import MainNavigation from '@/components/navigation/MainNavigation'
import './globals.css'
import { Poppins } from 'next/font/google'
import MobileNavigation from '@/components/navigation/MobileNavigation'

const poppins = Poppins({ subsets: ['latin'], weight: '400' })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
		<html lang="en">
			<body className={poppins.className}>
				<MainNavigation />
				<MobileNavigation />
				<div className='relative top-[100px]'>
					{children}
				</div>
			</body>
		</html>
    )
}
